settings:
  animation-tick-rate: 1
  display-interpolation-duration: 6
  center-interaction-hitbox: true
  command-dispatch-delay-ticks: 1
  default-scale: 3.0
  default-hitbox-width: 2.0
  default-hitbox-height: 2.0
  default-spin: true
  default-spin-speed: 2.0
  default-bob: true
  default-bob-height: 0.15
  default-bob-speed: 0.05
  default-collision: interaction
  click-cooldown-ms: 1000
  remove-orphan-plugin-entities-on-startup: true
  barrier-max-blocks: 512

display-defaults:
  glow: false
  command-executor: console
  permission: none
